################################################################
#  Collector: telegraf-jcy-rtr-02
#  Targets:
#    [netpanda-jcy-rtr-02]
#        interface = "gnmi"
#        interface_ethernet = "gnmi"
#        bgp = "execd"
#        cpu = "snmp"
#        memory = "snmp"
#        storage = "snmp"
#        uptime = "snmp"
#
################################################################
[global_tags]
  environment = "${ENVIRONMENT}"


[agent]
  hostname = "telegraf-jcy-rtr-02"

################################################################
#  Outputs
################################################################




  # ------------------------------
  # Prometheus Output
  # ------------------------------

  [[outputs.prometheus_client]]
    listen = ":9006"
    metric_version = 2
    expiration_interval = "120s"
    fielddrop = ["cbgpPeer2LastError"]
    tagexclude = ["index", "agent_host"]


################################################################
#  Inputs
################################################################

# ---------------------------------------------------------------------
# Input Internal Plugin
# ---------------------------------------------------------------------
# Collect Telegraf Internal Statistics
# - collection/execution time per plugin
# - metrics gathered
# - Memory usage
# and more
[[inputs.internal]]
  collect_memstats = true
  [inputs.internal.tags]
    telegraf_type="network_agent"

# ---------------------------------------------------------------------
# Inputs Definitions
# ---------------------------------------------------------------------


# ---------------------------------------------------------------------
# Input Net Response Plugin
# ---------------------------------------------------------------------
[[inputs.net_response]]
  protocol = "tcp"
  address = "netpanda-jcy-rtr-02:22"

  [inputs.net_response.tags]
    collection_method = "tcp_ping"
    device = "netpanda-jcy-rtr-02"
    device_role = "edge"
    device_platform = "arista"
    site = "jcy"
    region = "networktocode"
    net_os = "eos"
# ------------------------------------------------
# Input - gNMI  netpanda-jcy-rtr-02
# ------------------------------------------------
[[inputs.gnmi]]
  addresses = ["netpanda-jcy-rtr-02:50051"]
  username = "${NETWORK_AGENT_USER}"
  password = "${NETWORK_AGENT_PASSWORD}"
  redial = "20s"
  tagexclude = [
      "identifier",
      "network_instances_network_instance_protocols_protocol_name",
      "afi_safi_name",
      "path",
      "source"
  ]

  [inputs.gnmi.tags]
    collection_method = "gnmi"
    device = "netpanda-jcy-rtr-02"
    device_role = "edge"
    device_platform = "arista"
    site = "jcy"
    region = "networktocode"
    net_os = "eos"
  # ---------------------------------------------------
  # Device Interface Counters (gNMI)
  # ---------------------------------------------------
  [[inputs.gnmi.subscription]]
    name = "interface"
    # origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    # origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/admin-status"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.gnmi.subscription]]
    name = "interface"
    # origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/oper-status"
    subscription_mode = "sample"
    sample_interval = "10s"
  # ---------------------------------------------------
  # Device Interface Ethernet Counters (gNMI)
  # ---------------------------------------------------
  [[inputs.gnmi.subscription]]
    name = "interface"
    # origin = "openconfig-if-ethernet"
    path = "/interfaces/interface/ethernet/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"
# ------------------------------------------------
# Input - Execd command  netpanda-jcy-rtr-02
# ------------------------------------------------
[[inputs.execd]]
  interval = "60s"
  signal = "SIGHUP"
  restart_delay = "10s"
  data_format = "influx"
  command = [
    '/usr/local/bin/network_agent',
    '-h',
    'netpanda-jcy-rtr-02',
    '-d',
    'arista_eos',
    '-c',
    'bgp_sessions::http',  ]
  [inputs.execd.tags]
    collection_method = "execd"
    device = "netpanda-jcy-rtr-02"
    device_role = "edge"
    device_platform = "arista"
    site = "jcy"
    region = "networktocode"
    net_os = "eos"
# ------------------------------------------------
# Input - SNMP  netpanda-jcy-rtr-02
# ------------------------------------------------

[[inputs.snmp]]
  agents = ["netpanda-jcy-rtr-02"]
  version = 2
  community = "${SNMPv2_COMMUNITY}"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [inputs.snmp.tags]
    collection_method = "snmp"
    device = "netpanda-jcy-rtr-02"
    device_role = "edge"
    device_platform = "arista"
    site = "jcy"
    region = "networktocode"
    net_os = "eos"
  # ----------------------------------------------
  # Device CPU polling (SNMP)
  # ----------------------------------------------
  [[inputs.snmp.table]]
    name = "cpu"

    [[inputs.snmp.table.field]]
      name = "name"
      oid = "HOST-RESOURCES-MIB::hrDeviceDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "used"
      oid = "HOST-RESOURCES-MIB::hrProcessorLoad"
  # ----------------------------------------------
  # Device Memory polling (SNMP)
  # ----------------------------------------------
  [[inputs.snmp.table]]
    name = "memory"

    # Partition name
    [[inputs.snmp.table.field]]
      name = "name"
      oid = "HOST-RESOURCES-MIB::hrStorageDescr"
      is_tag = true

    # Size in bytesof the data objects allocated to the partition
    [[inputs.snmp.table.field]]
      name = "allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageAllocationUnits"

    # Size of the partition storage represented by the allocation units
    [[inputs.snmp.table.field]]
      name = "size_allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageSize"

    # mount of space used by the partition represented by the allocation units
    [[inputs.snmp.table.field]]
      name = "used_allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageUsed"
  # ----------------------------------------------
  # Device Storage Partition Table polling (SNMP)
  # ----------------------------------------------
  [[inputs.snmp.table]]
    name = "storage"
    # oid = "HOST-RESOURCES-MIB::hrStorageTable"

    # Partition name
    [[inputs.snmp.table.field]]
      name = "name"
      oid = "HOST-RESOURCES-MIB::hrStorageDescr"
      is_tag = true

    # Size in bytes of the data objects allocated to the partition
    [[inputs.snmp.table.field]]
      name = "allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageAllocationUnits"

    # Size of the partition storage reporesented by the allocation units
    [[inputs.snmp.table.field]]
      name = "size_allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageSize"

    # Amount of space used by the partition represented by the allocation units
    [[inputs.snmp.table.field]]
      name = "used_allocation_units"
      oid = "HOST-RESOURCES-MIB::hrStorageUsed"
  # ------------------------------------------------
  # Device Uptime - SNMP  netpanda-jcy-rtr-02
  # ------------------------------------------------

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "RFC1213-MIB::sysUpTime.0"

################################################################
#  Processors
################################################################



  ################################################################
  #  Data normalization
  ################################################################


  # ---------------------------------------------------
  # Cleanup Interface Data ingested from GNMI
  # ---------------------------------------------------
  [[processors.rename]]
    order = 1
    namepass = ["interface"]

    [[processors.rename.replace]]
      tag = "name"
      dest = "interface"

    [[processors.rename.replace]]
      field = "in_crc_errors"
      dest = "in_fcs_errors"

    [[processors.rename.replace]]
      field = "in_errors"
      dest = "in_errors_pkts"

    [[processors.rename.replace]]
      field = "in_discards"
      dest = "in_discards_pkts"

    [[processors.rename.replace]]
      field = "out_errors"
      dest = "out_errors_pkts"

    [[processors.rename.replace]]
      field = "out_discards"
      dest = "out_discards_pkts"
  # ---------------------------------------------------
  # Normalize BGP Data
  # ---------------------------------------------------
  [[processors.rename]]
    order = 1
    namepass = ["bgp*"]

    [[processors.rename.replace]]
      field = "installed"
      dest = "prefixes_installed"

    [[processors.rename.replace]]
      field = "sent"
      dest = "prefixes_sent"

    [[processors.rename.replace]]
      field = "received"
      dest = "prefixes_received"
  # ---------------------------------------------------
  # Normalize the CPU data
  # ---------------------------------------------------
  [[processors.rename]]
    order = 1
    namepass = ["cpu"]

    [[processors.rename.replace]]
      field = "instant"
      dest = "used"
  # ---------------------------------------------------
  # Normalize the Memory data
  # ---------------------------------------------------
  [[processors.rename]]
    order = 1
    namepass = ["memory"]

    [[processors.rename.replace]]
      field = "available"
      dest = "free"

    [[processors.rename.replace]]
      field = "utilized"
      dest = "used"
  # ---------------------------------------------------
  # Normalize BGP Data
  # ---------------------------------------------------
  [[processors.starlark]]
    order = 1
    namepass = ["bgp_session*"]
    source = '''
def apply(metric):
    metric.tags.pop("session_state")
    return metric
'''

  [[processors.rename]]
    order = 2
    namepass = ["bgp_session*"]

    [[processors.rename.replace]]
      field = "session_state_code"
      dest = "state"

  [[processors.rename]]
    order = 3
    namepass = ["bgp_session*"]

    [[processors.rename.replace]]
      measurement = "bgp_sessions"
      dest = "bgp_session"

  # ---------------------------------------------------
  # Normalize Memory data
  # ---------------------------------------------------
  [[processors.starlark]]
    order = 2
    namepass = ["memory", "storage"]
    source = '''
def apply(metric):
    if 'allocation_units' in metric.fields:
        metric.fields['total'] = metric.fields['size_allocation_units'] * metric.fields['allocation_units']
        metric.fields['used'] = 100 * (metric.fields['used_allocation_units'] * metric.fields['allocation_units']) / metric.fields['total']
        metric.fields['free'] = 100 - metric.fields['used']
        for field_type in ['size_allocation_units', 'allocation_units', 'used_allocation_units']:
            metric.fields.pop(field_type)
        return metric
'''
    [processors.starlark.tagpass]
      collection_method = ["snmp"]
      net_os = ["eos"]


  # TODO: To be fixed with new network agents image
  # [[processors.override]]
  #   order = 10
  #   namepass = ["memory"]
  #   fielddrop = ["*"]

  #   [processors.override.tagdrop]
  #     name = ["RAM*"]




  # ---------------------------------------------------
  # Normalize Uptime Measurement (SNMP)
  # ---------------------------------------------------
  [[processors.rename]]
    order = 1
    namepass = ["snmp"]

    [[processors.rename.replace]]
      measurement = "snmp"
      dest = "environment"

  # ---------------------------------------------------
  # Normalize status codes
  # ---------------------------------------------------
  [[processors.enum]]
    order = 3
    namepass = ["bgp"]

    [[processors.enum.mapping]]
      ## Name of the field to map
      field = "session_state"

      [processors.enum.mapping.value_mappings]
        IDLE = 1
        CONNECT = 2
        ACTIVE = 3
        OPENSENT = 4
        OPENCONFIRM = 5
        ESTABLISHED = 6
  [[processors.enum]]
    order = 3
    namepass = ["interface"]

    [[processors.enum.mapping]]
      ## Name of the field to map
      field = "oper_status"
      [processors.enum.mapping.value_mappings]
        UP = 1
        DOWN = 2
        TESTING = 3
        UNKNOWN = 4
        DORMANT = 5
        NOT_PRESENT = 6
        LOWER_LAYER_DOWN = 7

    [[processors.enum.mapping]]
      field = "admin_status"
      [processors.enum.mapping.value_mappings]
        UP = 1
        DOWN = 2
        TESTING = 3
  [[processors.enum]]
    order = 3
    namepass = ["storage"]

    [[processors.enum.mapping]]
      tag = "status"
      [processors.enum.mapping.value_mappings]
        1 = "READ_ONLY"
        2 = "RUN_FROM_FLASH"
        3 = "READ_WRITE"


  ################################################################
  #  Data enrichment
  ################################################################





  # ---------------------------------------------------
  # Data Interface Enrichment: netpanda-jcy-rtr-02
  # ---------------------------------------------------
  [[processors.regex]]
    order = 3
    namepass = ["interface"]

    [processors.regex.tagpass]
      device = ["netpanda-jcy-rtr-02"]

    [[processors.regex.tags]]
        key = "interface"
        pattern = "^Management1$"
        replacement = "mgmt"
        result_key = "interface_role"
    [[processors.regex.tags]]
        key = "interface"
        pattern = "^Loopback0$"
        replacement = "router_id"
        result_key = "interface_role"
    [[processors.regex.tags]]
        key = "interface"
        pattern = "^Ethernet3$"
        replacement = "backbone"
        result_key = "interface_role"
    [[processors.regex.tags]]
        key = "interface"
        pattern = "^Ethernet4$"
        replacement = "peer"
        result_key = "interface_role"
    [[processors.regex.tags]]
        key = "interface"
        pattern = "^Ethernet5$"
        replacement = "spine"
        result_key = "interface_role"


